---
roles:
  master:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provider:
      type: virtualbox
      customize:
        - [modifyvm, !ruby/sym id, '--memory', 1024]
    synced_folders: 
      - {host_path:  'puppet', guest_path: '/root/puppet'}
    provisioners:
      - type: shell
        inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"
      - type: hosts
      - type: pe_bootstrap
        role: :master
      - type: shell
        inline: |-
          /opt/puppet/bin/puppet apply \
            --confdir=/root/puppet \
            --ssldir=/etc/puppetlabs/puppet/ssl \
            --hiera_config=/root/puppet/hiera.yaml \
            --modulepath=/root/puppet/modules \
            --exec 'include role::puppetmaster'

  windows_agent:
    guest: windows
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provisioners:
      - {type: hosts}
      - {type: pe_bootstrap}

  posix_agent:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provisioners:
      - {type: shell, inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"}
      - {type: hosts}
      - {type: pe_bootstrap}
