---
vms:
  - name: "master"
    box:  "centos-64-x64-vbox4210-nocm"
    roles: [ "master" ]

  - name: "centos59a"
    box: "centos-59-x64-vbox4210-nocm"
    roles: [ "posix_agent" ]

  - name: "centos64a"
    box: "centos-64-x64-vbox4210-nocm"
    roles: [ "posix_agent" ]

  - name: "centos64b"
    box: "centos-64-x64-vbox4210-nocm"
    roles: [ "posix_agent" ]

  - name: "debian607a"
    box: "debian-607-x64-vbox4210-nocm"
    roles: [ "posix_agent" ]

  - name: "ubuntu1204a"
    box: "ubuntu-server-12042-x64-vbox4210-nocm"
    roles: [ "posix_agent" ]

# The remainder of these boxes use commercial platforms for which this project
# does not distribute boxfiles. They can be enabled by defining an appropriate
# box in the boxes.yaml file, and then uncommenting out these blocks below.

# - name: "sles11a"
#   box: "sles-11sp1-x64-vbox4210-nocm"
#   roles: [ "posix_agent" ]

# - name: "solaris10a"
#   box: 'solaris-10u9-x64'
#   roles: [ "posix_agent" ]

# - name: "server2008r2a"
#   box: "windows-server-2008-r2-x64-v2"
#   roles: [ "windows_agent" ]
#   forwarded_ports:
#     - { guest: 5985, host: 5985 }
#     - { guest: 3389, host: 3389 }

# - name: "server2008r2b"
#   box: "windows-server-2008-r2-x64"
#   roles: [ "windows_agent" ]
#   forwarded_ports:
#     - { guest: 5985, host: 5986 }
#     - { guest: 3389, host: 3390 }
